// It appears that Google does not like C++ protobuf messages and gRpc stubs to be
// used in a shared dynamic library (otherwise they'd tell us how to __declspec(dllexport) the
// message/service classes through protoc), so we'll just include the autogenerated sources

#include "../../gRpc/cxx/Common.grpc.pb.cc"
#include "../../gRpc/cxx/Common.pb.cc"
#include "../../gRpc/cxx/Fdo.grpc.pb.cc"
#include "../../gRpc/cxx/Fdo.pb.cc"
#include "../../gRpc/cxx/FeatureService.grpc.pb.cc"
#include "../../gRpc/cxx/FeatureService.pb.cc"
#include "../../gRpc/cxx/FeatureSource.grpc.pb.cc"
#include "../../gRpc/cxx/FeatureSource.pb.cc"
#include "../../gRpc/cxx/LayerDefinition.grpc.pb.cc"
#include "../../gRpc/cxx/LayerDefinition.pb.cc"
#include "../../gRpc/cxx/MapDefinition.grpc.pb.cc"
#include "../../gRpc/cxx/MapDefinition.pb.cc"
#include "../../gRpc/cxx/RenderingService.grpc.pb.cc"
#include "../../gRpc/cxx/RenderingService.pb.cc"
#include "../../gRpc/cxx/ResourceService.grpc.pb.cc"
#include "../../gRpc/cxx/ResourceService.pb.cc"